### ISSUE TITLE
investigate why a refresh of UI is (sometimes) needed to load members (and sometimes messages)

### ISSUE THREAD

**Issue by jdeepee** [fluxsocial/flux#224]
- Could be that the gql caching is still partly on at the client side? 
- Caching on the ad4m-executor server side? Which gets refreshed when a new client connection is created?

**Comment by kaichaosun** [comment]
Not sure if related, I got this error while waiting for message arrive,

![image](https://user-images.githubusercontent.com/10568673/153234716-cc411a9c-b2fd-4bcb-8743-ab8a606f3991.png)
